#!/bin/sh

## logs
for f in 0 emacs net uim wm; do echo "" >"$HOME/log/$f"; done

## vars
export PATH="$HOME/bin${PATH:+:}$PATH"
export BROWSER=icecat
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"
#export _JAVA_AWT_WM_NONREPARENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=lcd -Dsun.java2d.xrender=true -Dswing.aatext=true'
export MOZ_DISABLE_PANGO=1
export GTK_IM_MODULE=uim
export QT_IM_MODULE=uim
export XMODIFIERS='@im=uim'
#export QT_QPA_PLATFORMTHEME=qt5ct

## settings
sudo 0lum $(expr $(cat /sys/class/backlight/intel_backlight/max_brightness) '/' 2 '-' 32 '*' 8) >"$HOME/log/0" &
0hot kbd base
alsactl --file "$HOME/.config/asound.state" restore &
xmodmap "$HOME/cfg/hsnt.xmodmap" & # opp: setxkbmap -option ctrl:nocaps
xset fp+ "$HOME/.local/share/fonts/bitmap" fp rehash &
xsetroot -cursor_name left_ptr -solid '#657b83' &

## services
{ 0mon 2>>"$HOME/log/0" | \
  lemonbar -d -f 'Iosevka:bold:pixelsize=13' -g x20 -n lemonbar -p -B '#eee8d5' -F '#93a1a1' >>"$HOME/log/wm" & } &
bgon 0 0browsertmp
#bgon net blueman-applet
bgon wm dunst
bgon emacs emacs --daemon
sleep 2 && bgon wm stalonetray --background '#eee8d5' --geometry 1x1-0+0 --grow-gravity E --icon-gravity E --icon-size 20 --kludges force_icons_size --skip-taskbar --sticky
#bgon uim uim-toolbar-gtk-systray
#bgon uim uim-xim
bgon net wicd-client --no-animate --tray

## window manager
exec dbus-launch --exit-with-session cwm
