colorscheme cemant
set-option global grepcmd 'rg --line-number --with-filename'
set-option global indentwidth 2
set-option global modelinefmt '{StatusLineInfo}%sh{expr >/dev/null "${#kak_bufname}" ">" `expr \`tput cols\` "/" 2` && printf "$kak_bufname" | sed "s_[^/]\+\$__" | sed "s_\([^/]\{,2\}\)[^/]*/_\1/_g" || printf "$kak_bufname" | sed "s_[^/]\+\$__"}{black,white}%sh{printf "$kak_bufname" | sed "s_^.*/__"}{StatusLineInfo}:%val{buf_line_count}/{black}%val{cursor_line}{StatusLineInfo}:{black}%val{cursor_char_column}{{context_info}} {{mode_info}}'
set-option global tabstop 2
set-option global ui_options ncurses_assistant=none ncurses_enable_mouse=yes ncurses_set_title=yes ncurses_status_on_top=yes
add-highlighter global/ number-lines -hlcursor -separator ' '
add-highlighter global/ regex \h+$ 0:Error
add-highlighter global/ regex '(FIXME|NOTE|TODO|WIP|XXX)' 0:black,bright-blue+F
add-highlighter global/ show-matching
add-highlighter global/ wrap
define-command -buffer-completion d "delete-buffer" -docstring 'delete current buffer'
map global normal <minus> vk        -docstring 'scroll up one'
map global normal <=>     vj        -docstring 'scroll down one'
map global normal <_>     8vk       -docstring 'scroll up eight'
map global normal <+>     8vj       -docstring 'scroll down eight'
map global normal <'>     _         -docstring 'trim'
map global normal </>     /(?i)     -docstring 'uncased search'
map global normal <a-/>   <a-/>(?i) -docstring 'uncased reverse search'
map global normal <?>     ?(?i)     -docstring 'uncased extended search'
map global normal <a-?>   <a-?>(?i) -docstring 'uncased extended reverse search'
map global normal <space> ':set-register slash ""<ret>' -docstring 'empty out search register'
map global normal <a-space> '' # unmap not working :-/
map global normal <a-d>   Xd        -docstring 'delete extended line'
map global normal <c-g>   <space>   -docstring 'remove secondary selections'
map global normal <c-a-g> <a-space> -docstring 'remove primary selection'
map global normal <n>     nvc       -docstring 'select next search pattern and center view'
map global normal <s-n>   Nvc       -docstring 'extend with next search pattern and center view'
map global normal <a-n>   <a-n>vc   -docstring 'select previous search pattern and center view'
map global normal <a-s-n> <a-s-n>vc -docstring 'extend with previous search pattern and center view'
map global normal <c-p> '!wl-paste<space>--no-newline<ret>:echo -markup "{Information}pasted from clipboard"<ret>' -docstring 'paste clipboard'
map global normal <a-v>   <c-b>     -docstring 'scroll up page'
map global normal <c-v>   <c-f>     -docstring 'scroll down page'
map global normal <c-y> '<a-|>wl-copy<ret>:echo -markup "{Information}yanked to clipboard"<ret>' -docstring 'yank selection into clipboard'

