[terminal]
vt = "next"

[default_session]
command = "tuigreet --asterisks --power-reboot 'doas /usr/sbin/reboot' --power-shutdown 'doas /usr/sbin/shutdown' --remember --remember-session --time --width 96 --window-padding 12 --cmd 'dbus-run-session niri --session >/home/b/log/niri.log 2>&1'"
user = "_greeter"

[initial_session]
command = "dbus-run-session niri --session >/home/b/log/niri.log 2>&1"
user = "b"

