[terminal]
vt = "next"

[default_session]
command = "tuigreet --asterisks --power-reboot 'doas /usr/sbin/reboot' --power-shutdown 'doas /usr/sbin/shutdown' --remember --remember-session --time --width 96 --window-padding 12 --cmd /usr/sbin/hyprland"
user = "_greeter"

[initial_session]
command = "/usr/sbin/hyprland"
user = "b"

